distributed.nanny - INFO -         Start Nanny at: 'tcp://10.120.40.89:35665'
distributed.worker - INFO -       Start worker at:   tcp://10.120.40.89:38442
distributed.worker - INFO -          Listening to:   tcp://10.120.40.89:38442
distributed.worker - INFO -          dashboard at:         10.120.40.89:44485
distributed.worker - INFO - Waiting to connect to:   tcp://10.120.43.21:41954
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    8.00 GB
distributed.worker - INFO -       Local Directory: /home/ad/alberta/dask-worker-space/worker-t_lkyamk
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://10.120.43.21:41954
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
tornado.application - ERROR - Exception in callback <function Worker.__init__.<locals>.<lambda> at 0x2b045ff2b510>
Traceback (most recent call last):
  File "/home/ad/alberta/.conda/envs/perf-pangeo/lib/python3.6/site-packages/tornado/ioloop.py", line 907, in _run
    return self.callback()
  File "/home/ad/alberta/.conda/envs/perf-pangeo/lib/python3.6/site-packages/distributed/worker.py", line 644, in <lambda>
    lambda: self.batched_stream.send({"op": "keep-alive"}), 60000,
  File "/home/ad/alberta/.conda/envs/perf-pangeo/lib/python3.6/site-packages/distributed/batched.py", line 117, in send
    raise CommClosedError
distributed.comm.core.CommClosedError
distributed.worker - INFO - Stopping worker at tcp://10.120.40.89:38442
distributed.nanny - INFO - Worker closed
distributed.dask_worker - INFO - Exiting on signal 15
distributed.nanny - INFO - Closing Nanny at 'tcp://10.120.40.89:35665'
distributed.dask_worker - INFO - End worker
